name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: find "$(pwd)"  -name go.mod -print0 | xargs -n 1 -0 -I{} dirname {} |  xargs -L 1 bash -c 'cd $0 && go test ./...'
        continue-on-error: false

      - name: Test
        run: find "$(pwd)"  -name go.mod -print0 | xargs -n 1 -0 -I{} dirname {} |  xargs -L 1 bash -c 'cd $0 && go test ./...'
        continue-on-error: false
